### ISSUE TITLE
IDEA: Better logging in Rails logger

### ISSUE THREAD

**Issue by emilebosch** [emilebosch/graphql-hackathon-ams#8]
Right now the output from the graphql queries in the logger looks like a massive massive post string. It would be nice to make that somehow look (nicer/nested/coloured?), and even maybe with stats per resolver.

**Comment by jpserra** [comment]
@emilebosch This is very interesting, have you dedicated any time trying to figure it out?

**Comment by emilebosch** [comment]
Yeah  trivial to implement now with new tracing api that came out the hackathon
